"""change top date to date object

Revision ID: 144a84764f17
Revises: b3861d8508a4
Create Date: 2017-08-17 17:32:55.810504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144a84764f17'
down_revision = 'b3861d8508a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tops', sa.Column('held_on', sa.Date(), nullable=True))
    op.drop_column('tops', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tops', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tops', 'held_on')
    # ### end Alembic commands ###
