"""add duration to tops

Revision ID: 22e250df9edb
Revises: 41602affeba6
Create Date: 2017-08-17 16:07:41.760348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e250df9edb'
down_revision = '41602affeba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tops', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tops', 'duration')
    # ### end Alembic commands ###
