"""add date to tops

Revision ID: 26c5f847ffbe
Revises: c63b6ebf220a
Create Date: 2017-08-17 16:58:49.459789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c5f847ffbe'
down_revision = 'c63b6ebf220a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tops', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tops', 'date')
    # ### end Alembic commands ###
