"""add job category for MdB

Revision ID: 3607a45ec9ea
Revises: 144a84764f17
Create Date: 2017-08-26 16:01:07.116587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3607a45ec9ea'
down_revision = '144a84764f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mdb', sa.Column('job_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mdb', 'job_category')
    # ### end Alembic commands ###
