"""categories to number

Revision ID: 37d3ae618d8f
Revises: c586d5db18d1
Create Date: 2017-08-11 19:52:39.345722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d3ae618d8f'
down_revision = 'c586d5db18d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
