"""little test

Revision ID: 3b5a48fd70c9
Revises: ec1e31bd0d63
Create Date: 2017-08-17 17:29:15.175550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5a48fd70c9'
down_revision = 'ec1e31bd0d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
