"""add agw id to mdb

Revision ID: 41602affeba6
Revises: d52541d3c0ec
Create Date: 2017-08-15 18:04:08.469761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41602affeba6'
down_revision = 'd52541d3c0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('de_bundestag_plpr', sa.Column('agw_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('de_bundestag_plpr', 'agw_id')
    # ### end Alembic commands ###
