"""expand top table

Revision ID: 5cf24c730ef9
Revises: c41a3381b936
Create Date: 2017-08-11 16:15:23.852522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf24c730ef9'
down_revision = 'c41a3381b936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tops', sa.Column('categories', sa.Integer(), nullable=True))
    op.add_column('tops', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tops', sa.Column('detail', sa.String(), nullable=True))
    op.add_column('tops', sa.Column('number', sa.String(), nullable=True))
    op.add_column('tops', sa.Column('title_clean', sa.String(), nullable=True))
    op.add_column('tops', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('tops', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tops', 'year')
    op.drop_column('tops', 'week')
    op.drop_column('tops', 'title_clean')
    op.drop_column('tops', 'number')
    op.drop_column('tops', 'detail')
    op.drop_column('tops', 'description')
    op.drop_column('tops', 'categories')
    # ### end Alembic commands ###
