"""categories to string

Revision ID: 6ac4489caae2
Revises: 37d3ae618d8f
Create Date: 2017-08-11 20:03:33.494971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac4489caae2'
down_revision = '37d3ae618d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
