"""expand top table

Revision ID: 6f3bf3cb8744
Revises: bb560565633d
Create Date: 2017-08-11 18:11:03.756472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3bf3cb8744'
down_revision = 'bb560565633d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'de_bundestag_plpr_top_id_fkey', 'de_bundestag_plpr', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'de_bundestag_plpr_top_id_fkey', 'de_bundestag_plpr', 'tops', ['top_id'], ['id'])
    # ### end Alembic commands ###
