"""categories to string

Revision ID: 7243c5f6cadf
Revises: 6ac4489caae2
Create Date: 2017-08-11 20:05:04.441669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7243c5f6cadf'
down_revision = '6ac4489caae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
