"""expand top table

Revision ID: b21f0915dc27
Revises: fde269efe0c4
Create Date: 2017-08-15 16:29:27.418495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21f0915dc27'
down_revision = 'fde269efe0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
