"""change top date to date object

Revision ID: b3861d8508a4
Revises: 3b5a48fd70c9
Create Date: 2017-08-17 17:30:10.833067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3861d8508a4'
down_revision = '3b5a48fd70c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
