"""top table foreignkey change

Revision ID: bb560565633d
Revises: 5cf24c730ef9
Create Date: 2017-08-11 17:43:41.308506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb560565633d'
down_revision = '5cf24c730ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
