"""change primary key of top table

Revision ID: bfd2ac971ad5
Revises: b21f0915dc27
Create Date: 2017-08-15 16:30:59.284793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd2ac971ad5'
down_revision = 'b21f0915dc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
