"""delete foreign key

Revision ID: c586d5db18d1
Revises: 6f3bf3cb8744
Create Date: 2017-08-11 18:11:36.962553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c586d5db18d1'
down_revision = '6f3bf3cb8744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
