"""rename agw_id to speaker_key

Revision ID: c63b6ebf220a
Revises: 22e250df9edb
Create Date: 2017-08-17 16:11:47.105652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63b6ebf220a'
down_revision = '22e250df9edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('de_bundestag_plpr', sa.Column('speaker_key', sa.Integer(), nullable=True))
    op.drop_column('de_bundestag_plpr', 'agw_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('de_bundestag_plpr', sa.Column('agw_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('de_bundestag_plpr', 'speaker_key')
    # ### end Alembic commands ###
