"""change top date to date object

Revision ID: d9e7cc2f8fbd
Revises: f122c6c4a70e
Create Date: 2017-08-17 17:21:49.536269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e7cc2f8fbd'
down_revision = 'f122c6c4a70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
