"""rename category

Revision ID: e4d35f5252cf
Revises: 7243c5f6cadf
Create Date: 2017-08-11 20:06:27.147309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d35f5252cf'
down_revision = '7243c5f6cadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tops', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('tops', 'categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tops', sa.Column('categories', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tops', 'category')
    # ### end Alembic commands ###
