"""change primary key of top table

Revision ID: e93ed69447d8
Revises: bfd2ac971ad5
Create Date: 2017-08-15 16:31:33.389209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93ed69447d8'
down_revision = 'bfd2ac971ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
