"""change top date to date object

Revision ID: ec1e31bd0d63
Revises: d9e7cc2f8fbd
Create Date: 2017-08-17 17:28:37.795022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1e31bd0d63'
down_revision = 'd9e7cc2f8fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
