"""change top date to date object

Revision ID: f122c6c4a70e
Revises: 26c5f847ffbe
Create Date: 2017-08-17 17:18:27.165584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f122c6c4a70e'
down_revision = '26c5f847ffbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
