"""rename job category

Revision ID: f31e2387c73a
Revises: 3607a45ec9ea
Create Date: 2017-08-26 16:03:36.233606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31e2387c73a'
down_revision = '3607a45ec9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mdb', sa.Column('education_category', sa.String(), nullable=True))
    op.drop_column('mdb', 'job_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mdb', sa.Column('job_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mdb', 'education_category')
    # ### end Alembic commands ###
