"""expand top table

Revision ID: fde269efe0c4
Revises: e4d35f5252cf
Create Date: 2017-08-14 12:15:18.044273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde269efe0c4'
down_revision = 'e4d35f5252cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('election_list', sa.String(), nullable=True),
    sa.Column('list_won', sa.String(), nullable=True),
    sa.Column('top_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'de_bundestag_plpr', sa.Column('speaker_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'de_bundestag_plpr', 'speaker_id')
    op.drop_table('mdb')
    # ### end Alembic commands ###
